<script type="text/javascript">
    $(function(){
        $(".menu li a").removeClass("active");
        $(".menu-episodes").addClass("active");
    })
</script>
<div class="wrap">
    <div class="page">
        <div class="video-item">
            <div class="info">
                <h3>Епізод 4</h3>
                <p>Заключний зимовий епізод сезону 2013/14. За останній місяць у нас відобулось багато подій. Кемп Sunny Days в Буковелі, який для багатьох став закриттям сезону в Україні. Пригоди в Європі і сноупарки в Італії.
                    Тепер готуємось до літа, перший крок це був ремонт скейтпарку в Івано-Франківську.</p>
            </div>
            <iframe src="//player.vimeo.com/video/93841662" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="video-item">
            <div class="info">
                <h3>Епізод 3</h3>
                <p>Подорожі в пошуках снігу і спотів продовжуються. Цього разу це Львів і новостворений парк в Горбово. Хоча сьогодні перший день весни, ми не думаєм навіть зупинятись кататись.</p>
            </div>
            <iframe src="//player.vimeo.com/video/87858029" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="video-item">
            <div class="info">
                <h3>Епізод 2</h3>
                <p>Довгоочікуваний сніг нарешті прийшов у міста і ми перебрались з парків на вулиці. В цьому епізоді - справжній мокрий джибінг в буковельському парку, нічний стріт в Івано-Франківську і локал спот на дачі.</p>
            </div>
            <iframe src="//player.vimeo.com/video/86026621" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="video-item">
            <div class="info">
                <h3>Епізод 1</h3>
                <p>Перший епізод - це початок сезону 2013/14 року. Ситуація зі снігом в містах майже безнадійна, тому ми катається в сноупарку Буковель.</p>
            </div>
            <iframe src="//player.vimeo.com/video/84203277" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
    </div>
</div>