<div class="promo">
    <div class="bg">
        <div class="wrap">
            <iframe src="//player.vimeo.com/video/105065450" width="720" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
    </div>
</div>
<div class="wrap">

            <div class="part p1">
                <h1>CORE новини</h1>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
            </div>
            <div class="part p2">
                <h1>Рекомендуємо</h1>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
                <div class="news-item">
                    <div class="hover"></div>
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <div class="add">
                        <div class="line">
                            <a href="" class="author">Саша Косторниченко</a>
                            <span class="date">32.54.2005</span>
                        </div>
                        <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                    </div>
                </div>
            </div>

    </div>
<!--    <div class="sidebar">

    </div>
-->