<div class="promo">
    <div class="wrap">

    </div>
</div>
<div class="wrap">
    <div class="column">
        <div class="news">
            <div class="part">
                <h1>CORE новини</h1>
                <div class="news-item">
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <span class="line">
                        <a href="" class="author">Саша Косторниченко</a>
                        <span class="date">32.54.2005</span>
                    </span>
                    <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                </div>
                <div class="news-item">
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <span class="line">
                        <a href="" class="author">Саша Косторниченко</a>
                        <span class="date">32.54.2005</span>
                    </span>
                    <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                </div>
                <div class="news-item">
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <span class="line">
                        <a href="" class="author">Саша Косторниченко</a>
                        <span class="date">32.54.2005</span>
                    </span>
                    <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                </div>
                <div class="news-item">
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <span class="line">
                        <a href="" class="author">Саша Косторниченко</a>
                        <span class="date">32.54.2005</span>
                    </span>
                    <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                </div>
            </div>
            <div class="part">
                <h1>Рекомендуємо</h1>
                <div class="news-item">
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <span class="line">
                        <a href="" class="author">Саша Косторниченко</a>
                        <span class="date">32.54.2005</span>
                    </span>
                    <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                </div>
                <div class="news-item">
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <span class="line">
                        <a href="" class="author">Саша Косторниченко</a>
                        <span class="date">32.54.2005</span>
                    </span>
                    <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                </div>
                <div class="news-item">
                    <a href="" class="img"><img src="http://i.vimeocdn.com/video/442120109_640.jpg" alt=""/></a>
                    <span class="line">
                        <a href="" class="author">Саша Косторниченко</a>
                        <span class="date">32.54.2005</span>
                    </span>
                    <a href="" class="title">LINE Traveling Circus 6.8 Everybody Loves Ramen</a>
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar">

    </div>
</div>