<script type="text/javascript">
    $(function(){
        $(".menu li a").removeClass("active");
    })
</script>
<div class="wrap">
    <div class="page">
        <div class="news">
            <h1>Заголовок публікації</h1>
            <img src="/images/crew.jpg" alt="fsdafsa"/>
            <div class="pre">
                <div class="item">Автор:
                    <a href="">Степан тоорп</a>
                </div>
                <div class="item">Категорії:
                    <a href="">Звіт</a>
                    <a href="">Сноуборд</a>
                </div>
                <div class="item">Теги:
                    <a href="">#гори</a>
                    <a href="">#буковель</a>
                    <a href="">#сноуборд</a>
                    <a href="">#скейтборд</a>
                </div>
            </div>
            <div class="text">
                <p>Мы видели работы московских видеопродакшнов, питерских крю и сибирских самородков. Но на днях к нам прилетели вести с Урала: местные ребята сняли видеопроект и готовы показать нам свой первый тизер. Какой уровень катания и съемок на Урале? Рассказывают сами создатели фильма.</p>
                <p>Мы видели работы московских <img src="/images/crew.jpg" alt="fsdafsa"/>видеопродакшнов, питерских крю и сибирских самородков. Но на днях к нам прилетели вести с Урала: местные ребята сняли видеопроект и готовы показать нам свой первый тизер. Какой уровень катания и съемок на Урале? Рассказывают сами создатели фильма.</p>
                <p>Мы видели работы московских видеопродакшнов, питерских крю и сибирских <a href="">крю и сибирских самородков.</a>самородков. Но на днях к нам прилетели вести с Урала: местные ребята сняли видеопроект и готовы показать нам свой первый тизер. Какой уровень катания и съемок на Урале? Рассказывают сами создатели фильма.</p>
            </div>
            <iframe src="//player.vimeo.com/video/80452815" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="social">
            <div class="item">
                <div id="vk_like"></div>
                <script type="text/javascript">
                    VK.Widgets.Like("vk_like", {type: "button"});
                </script>
            </div>
            <div class="item">
                <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
            </div>
            <div class="item">
                <a class="twitter-share-button"
                   href="https://twitter.com/share">
                    Tweet
                </a>
                <script type="text/javascript">
                    window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));
                </script>
            </div>
            <div class="item">
                <script src="https://apis.google.com/js/platform.js" async defer>
                    {lang: 'uk'}
                </script>
                <div class="g-plusone" data-size="medium"></div>
            </div>
        </div>
    </div>
</div>