<script type="text/javascript">
    $(function(){
        $(".menu li a").removeClass("active");
        $(".menu-video").addClass("active");
    })
</script>
<div class="wrap">
    <div class="page">
        <div class="video-item">
            <div class="info">
                <h3>Project 13</h3>
                <p><strong>2013</strong></p>
                <p><strong>Катаються:</strong>Бобелюк Марія, Бобелюк Роман, Голод Юра, Косторниченко Саша, Любінець Юра, Малецький Макс, Назарук Назар, Пецоляк Юра, Черкасюк Андрій та друзі</p>
                <p><strong>Знімали:</strong>Назарук Назар, команда КОР, IFRider</p>
                <p><strong>Монтаж:</strong>Назар Назарук</p>
                <p><strong>Зйомки проходили:</strong>Львів, Івано-Франківськ, Горбово, Карпати, Австрія</p>
            </div>
            <iframe src="//player.vimeo.com/video/80452815" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="video-item">
            <div class="info">
                <h3>Шерсть</h3>
                <p><strong>2012</strong></p>
                <p><strong>Катаються:</strong>Назар Назарук, Саша Косторниченко, Роман Бобелюк, Макс Малецький, Юра Олійник, Ігор Мельник, Стас Кодак та друзі</p>
                <p><strong>Знімали:</strong>команда КОР, Борис Віктюк, Роман Петрусяк, Маx Webb</p>
                <p><strong>Монтаж:</strong>Назар Назарук</p>
                <p><strong>Зйомки проходили:</strong>Львів, Івано-Франківськ, Київ, Горбово, Карпати, Австрія</p>
            </div>
            <iframe src="//player.vimeo.com/video/52185619" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="video-item">
            <div class="info">
                <h3>Колаж</h3>
                <p><strong>2011</strong></p>
                <p><strong>Катаються:</strong>Назар Назарук, Роман Бобелюк, Макс Малецький, Юля Ваховська, Саша Косторниченко, Міха Батир, Мирослав Нищей, Юра Олійник, Саша Корень, Стас Дех та друзі</p>
                <p><strong>Знімали:</strong>Назар Назарук, Роман Бобелюк, Денис Романчук, Борис Віктюк, Роман Петрусяк</p>
                <p><strong>Монтаж:</strong>Назар Назарук</p>
                <p><strong>Зйомки проходили:</strong>Львів, Івано-Франківськ, Карпати</p>
            </div>
            <iframe src="//player.vimeo.com/video/25374261" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
    </div>
</div>