<script type="text/javascript">
    $(function(){
        $(".menu li a").removeClass("active");
    })
</script>
<script src="http://login4play.com/assets/js/login4play.js" type="text/javascript"></script>
<div class="wrap">
    <div class="page">
        <div class="login">
            <div class="err"><?php echo $this->errMessage; ?></div>
            <?php echo $this->form; ?>
            <p>Увійти за допомогою соціальної мережі</p>
            <div id="login4play" login-data="redirect_uri=<?php echo urlencode("http://".$_SERVER['SERVER_NAME']."/auth/social"); ?>"></div>
        </div>
    </div>
</div>