<?php
require "lessphp/lessc.inc.php";
$less = new lessc;
$less->checkedCompile("less/admin.less", "css/admin.css");
?>
<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->escape($this->title)." | ".substr($this->serverUrl(), 7); ?></title>
    <meta charset="utf-8" http-equiv="content-type"/>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/admin.css'); ?>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</head>
<?php $user = Zend_Auth::getInstance()->getIdentity(); ?>
<body>
<div class="layout">
    <div class="header">
        <div class="wrap">
            <a class="logo" href="/admin"><span class="glyphicon glyphicon-home"></span>Панель администратора</a>
            <ul class="menu">
                <li><span class="glyphicon glyphicon-globe"></span><a target="_blank" href="/"><?php echo " ".$_SERVER['SERVER_NAME']; ?></a></li>
                <li><span class="glyphicon glyphicon-user"></span><a target="_blank" href="/user/<?php echo $user->login; ?>"><?php echo $user->login; ?></a></li>
                <li><span class="glyphicon glyphicon-log-out"></span><a href="/auth/logout">Выход</a></li>
            </ul>
        </div>
    </div>
    <div class="wrap">
        <div class="sidebar">

        </div>
        <div class="content">
            <h1><?php echo $this->escape($this->title); ?></h1>
            <div class="inner">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>
    <div class="hfooter"></div>
</div>
<div class="footer">
    <div class="wrap">
        footer
    </div>
</div>
</body>
</html>