<?php
require "lessphp/lessc.inc.php";
$less = new lessc;
$less->checkedCompile("less/style.less", "css/style.css");
?>
<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->escape($this->title); ?></title>
    <meta charset="utf-8" http-equiv="content-type"/>
    <meta name="description" content="<?php echo $this->escape($this->description)?>">
    <meta name="keywords" content="<?php echo $this->escape($this->keywords)?>">
    <link rel="stylesheet" href="/css/style.css"/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
</head>
<body>
<div class="layout">
<div class="header">
    <div class="top">
        <div class="wrap">
            <a href="" class="login">Вхід</a>
            <ul class="social">
                <li><a class="fb" href=""></a></li>
                <li><a class="vk" href=""></a></li>
                <li><a class="ig" href=""></a></li>
                <li><a class="vi" href=""></a></li>
            </ul>
        </div>
    </div>
    <div class="wrap">
        <a class="logo" href="/">coreproject.com.ua</a>
        <ul class="menu">
            <li><a class="active" href="">Головна</a><span>&#8226;</span></li>
            <li><a href="">Фото</a><span>&#8226;</span></li>
            <li><a href="">Відео</a><span>&#8226;</span></li>
            <li><a href="">Епізоди</a><span>&#8226;</span></li>
            <li><a href="">Новини</a><span>&#8226;</span></li>
            <li><a href="">Контакти</a><span>&#8226;</span></li>
            <li><a href="">Команда</a></li>
        </ul>
    </div>
</div>
<div class="content">
    <?php echo $this->layout()->content; ?>
</div>
    <div class="hfooter"></div>
</div>
<div class="footer">
    footer
</div>
</body>
</html>